<?php
/**
 * Shipping
 *
 * @package wooenvio/wecorreos
 */

return [
	'id'                   => 'paqlightinternational',
	'title'                => __( 'Paq Light International', 'correoswc' ),
	'description'          => __( 'Paq Light International', 'correoswc' ),
	'correos_code'         => 'S0360',
	'type_delivery'        => 'ST',
	'compatible_countries' => [
		'DE',
		'SA',
		'AW',
		'AU',
		'AT',
		'BB',
		'BE',
		'BR',
		'CA',
		'CZ',
		'CY',
		'KR',
		'HR',
		'DK',
		'DO',
		'SK',
		'SI',
		'EE',
		'FI',
		'FR',
		'GI',
		'GR',
		'HK',
		'HU',
		'IE',
		'IS',
		'IL',
		'IT',
		'JP',
		'JE',
		'LV',
		'LB',
		'LT',
		'LU',
		'MY',
		'MT',
		'MX',
		'NO',
		'NZ',
		'NL',
		'PL',
		'PT',
		'GB',
		'RU',
		'RS',
		'SG',
		'ZA',
		'SE',
		'CH',
		'TH',
		'TR',
	],
	'max_weight'           => 2,
	'class'                => 'WooEnvio\\WECorreos\\Infrastructure\\Common\\Shipping\\PaqLightInternational',
];
